os: osx

language: ruby

addons:
  homebrew:
    packages:
      - cabocha
      - gnuplot
      - graphviz
      - mecab

before_install:
  # Install Bundler 2.0
  - gem update --system
  - gem install bundler
  # Install Stanford CoreNLP
  - wget http://nlp.stanford.edu/software/stanford-corenlp-full-2018-10-05.zip
  - unzip stanford-corenlp-full-2018-10-05.zip
  - export PATH=$PATH:$PWD/stanford-corenlp-full-2018-10-05/

bundler_args: --without development

cache: bundler

before_script: bin/setup
